Layout/LineLength:
  Max: 120

Style/MultilineBlockChain:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15

Style/Documentation:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '*.gemspec'
    - '**/*.rake'
    - 'spec/**/*.rb'

AllCops:
  Exclude:
    - 'lib/em_easy_scraper/core_ext/*'
    - 'tmp/*'

