name: CI
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.0
          bundler-cache: true

      - name: Run rubocop
        run: |
          bundle exec rake rubocop

      - name: Run rspec
        env:
          REDIS_URL: redis://localhost:6379/0
        run: |
          bundle exec rake spec

